# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 10:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('course', models.CharField(max_length=100)),
                ('picturesList', models.CharField(max_length=1000)),
                ('attendanceList', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='CourseDB',
            fields=[
                ('emailID', models.CharField(max_length=100)),
                ('courseID', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EnrollmentDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=100)),
                ('courseID', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LogsDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeStamp', models.DateTimeField()),
                ('activities', models.CharField(max_length=1000)),
                ('userid', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PersonDB',
            fields=[
                ('userid', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('isTeacher', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='StudentFaceTokenDB',
            fields=[
                ('studentID', models.CharField(max_length=100)),
                ('face_token', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='TrainDB',
            fields=[
                ('studentID', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('picturesList', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='logsdb',
            unique_together=set([('timeStamp', 'userid')]),
        ),
        migrations.AlterUniqueTogether(
            name='enrollmentdb',
            unique_together=set([('userid', 'courseID')]),
        ),
        migrations.AlterUniqueTogether(
            name='attendancedb',
            unique_together=set([('date', 'course')]),
        ),
    ]
