# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 14:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProxyApp', '0002_auto_20170405_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancedb',
            name='attendanceList',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
