# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-07 06:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProxyApp', '0004_auto_20170406_0835'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollmentdb',
            name='cummulativeAttendance',
            field=models.IntegerField(default=0),
        ),
    ]
