# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-06 08:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProxyApp', '0003_auto_20170405_1410'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursedb',
            old_name='emailID',
            new_name='userid',
        ),
        migrations.AddField(
            model_name='persondb',
            name='emailID',
            field=models.CharField(default='niki.gollamudi@gmail.com', max_length=100),
        ),
    ]
